apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - image: mongo
      name: mongodb
      volumeMounts:
        - mountPath: /data/db
          name: mongodb
      ports:
        - containerPort: 27017
  volumes:
    - name: mongodb
      nfs:
        server: 10.0.2.5
        path: /home/nfs
